# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.IntegerField(choices=[(0, 'CLOSE'), (1, 'OPEN')], default=1),
        ),
        migrations.AlterField(
            model_name='trade',
            name='type_of',
            field=models.IntegerField(choices=[(1, 'BUY'), (2, 'SELL')], default=1),
        ),
    ]
