# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180205_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
